### ISSUE TITLE
Reverse engineer shadows

### ISSUE THREAD

**Issue by diegoliv** [tom2strobl/smooth-shadow#2]
First of all, thanks for this very helpful plugin! I created a Webflow plugin called [Better Shadows](https://bettershadowsforwebflow.webflow.io/) using it.

That said, one thing that I'd love to see is a reverse function of `getSmoothShadow()` (maybe called `getSmoothShadowProps()`?, where the input is a css shadow declaration, and the output is a list of properties values for distance, intensity, etc. For shadows that were not generated by the package, maybe just throw and error. Do you think that would be possible?

**Comment by tom2strobl** [comment]
Hi Diego, sorry for getting back to you so late — I don't see a way to do that in a performant manner. It's sort of like guessing a password from a hash.
I don't know your usecase, but maybe whenever a user changes the sliders your extension you cache input & output in a Map and then when you want to resolve an output you could look up the respective input in your map. Just be careful about memory limits and obviously this only works for values the user created in this session.
